spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lowercaseserviceid: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true


info:
  app:
    name: "gatewayserver"
    description: "Hans Bank gatewayserver Application"
    version: "1.0.0"


logging:
  level:
    com:
      hans:
        gatewayserver: DEBUG
